<?php
// $Id: network_connector.module,v 1.4 2009/09/08 19:12:20 btopro Exp $
//ELMS: Network Connector - Helper module to define path specific variables for use with the Network Manager module
//Copyright (C) 2009  The Pennsylvania State University
//
//Bryan Ollendyke
//bto108@psu.edu
//
//Keith D. Bailey
//kdb163@psu.edu
//
//12 Borland
//University Park,  PA 16802
//
//This program is free software; you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation; either version 2 of the License,  or
//(at your option) any later version.

//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU General Public License for more details.

//You should have received a copy of the GNU General Public License along
//with this program; if not,  write to the Free Software Foundation,  Inc.,
//51 Franklin Street,  Fifth Floor,  Boston,  MA 02110-1301 USA.

/**
 * @file
 * Variable set of the path to those drupal instance that runs on cron
 *
 *
 */

//This will reset itself on cron runs just to make sure this database is still on the same server address on the rare case that the site was moved from a dev to production environment
function network_connector_cron() {
  variable_set('network_connector_path','http://'. $_SERVER["HTTP_HOST"] . base_path());
}